# Generated by Django 2.1.8 on 2022-11-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('岗位', models.CharField(blank=True, max_length=32, null=True)),
                ('地点', models.CharField(blank=True, max_length=32, null=True)),
                ('薪资', models.CharField(blank=True, max_length=32, null=True)),
                ('工作经验', models.CharField(blank=True, max_length=32, null=True)),
                ('学历', models.CharField(blank=True, max_length=32, null=True)),
                ('公司', models.CharField(blank=True, max_length=32, null=True)),
                ('技能', models.CharField(blank=True, max_length=32, null=True)),
                ('区间最小薪资千', models.IntegerField(blank=True, db_column='区间最小薪资千', null=True)),
                ('城市地区', models.CharField(blank=True, max_length=32, null=True)),
                ('城市', models.CharField(blank=True, max_length=32, null=True)),
                ('地区', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'data1',
                'managed': False,
            },
        ),
    ]
