# Generated by Django 3.2 on 2023-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('岗位', models.CharField(blank=True, max_length=255, null=True)),
                ('地点', models.CharField(blank=True, max_length=32, null=True)),
                ('薪资', models.CharField(blank=True, max_length=32, null=True)),
                ('工作经验', models.CharField(blank=True, max_length=32, null=True)),
                ('学历', models.CharField(blank=True, max_length=32, null=True)),
                ('公司', models.CharField(blank=True, max_length=32, null=True)),
                ('技能', models.CharField(blank=True, max_length=32, null=True)),
                ('区间最小薪资千', models.IntegerField(blank=True, db_column='区间最小薪资千', null=True)),
                ('城市地区', models.CharField(blank=True, max_length=32, null=True)),
                ('城市', models.CharField(blank=True, max_length=32, null=True)),
                ('地区', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'search',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='data1',
            options={'managed': False, 'verbose_name': 'Python岗位数据', 'verbose_name_plural': 'Python岗位数据'},
        ),
    ]
